version: '3.8'
services:
  badgercam:
    build: .
    network_mode: "host"
#    ports:
#      - "9674:9674"
    volumes:
      - /opt/badgercam/settings.json:/home/badger/.badgercam/settings.json
      - /opt/badgercam/synced_videos:/home/badger/badgercam/src/web/public/synced_videos